-- db/seed.sql — 「法律小科普轻站」种子数据（Day 16）
-- 数据来源：data/cards.js（Day 8 定稿的 6 张 mock 卡），字段与 schema.sql 对齐。
-- 可重复执行：TRUNCATE 先清空（RESTART IDENTITY 同时重置 laws 自增 id），再 INSERT。
-- 注意：若单独重复执行本文件，要求表已由 schema.sql 建好。

TRUNCATE TABLE laws, cards RESTART IDENTITY CASCADE;

INSERT INTO cards
    (slug, title, summary, category, category_id, tags, scenario, solution_steps, related_slugs,
     published_at, updated_at, last_verified_at, author_type, reviewed_by, status)
VALUES
    ('gongsi-quantui',
     '公司劝退我，该怎么办？',
     '就像快递员说要「协商退货」——你可以答应，也可以拒收。公司说「你主动辞职吧」，主动权其实在你手里。',
     '劳动类', 'labor',
     '["劳动合同", "离职", "补偿金"]',
     '收到公司 HR 发来的「劝退」短信，暗示你主动辞职，否则调岗降薪。',
     '["先别签任何「自愿离职申请」——签了就拿不到补偿", "保留证据：聊天记录、录音、考勤、工资条", "算清应得补偿：每工作满 1 年补 1 个月工资", "协商不成，向当地劳动监察大队投诉或申请劳动仲裁"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published'),

    ('guoqi-shipin',
     '买到过期食品，除了退款还能索赔吗？',
     '就像买到坏掉的水果不止要换一份——过期食品是法律给消费者的「加倍保护」：退款之外，还可以主张价款十倍的赔偿。',
     '消费类', 'consume',
     '["食品安全", "索赔", "维权"]',
     '在便利店买了瓶酸奶，回家发现过期两天，店员说「退你钱就行了」。',
     '["保留小票、商品和包装（证据链第一环）", "先与商家协商：退货退款 + 主张赔偿", "协商不成，拨 12315 或在全国 12315 平台小程序投诉", "仍不解决，可向法院起诉（小额诉讼程序，成本低）"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published'),

    ('pengyou-jietiao',
     '朋友借钱，借条到底怎么写才有用？',
     '借条就像游戏里的「存档点」——写对了，以后吵翻天也能读档重来；写错了，可能连吵架的资格都没有。',
     '借贷类', 'loan',
     '["借条", "民间借贷", "证据"]',
     '好朋友急借 8000 元，说「咱俩这关系还要打借条？」你有点为难。',
     '["写清三要素：金额（大小写）、还款日期、双方姓名+身份证号", "利率别超过一年期 LPR 的 4 倍，超出部分法律不保护", "转账交付，备注「借款」，别给现金", "到期不还，3 年内必须主张（诉讼时效）"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published'),

    ('fangdong-bu-tui-yajin',
     '房东不退押金，一招制胜',
     '押金就像游戏里的「保证金」——只要你没损坏装备（房屋设施），通关（退租）时就得原样退还，少一分都可以较真。',
     '婚姻家庭类', 'marriage',
     '["租房", "押金", "合同"]',
     '退租时房东以「墙面有钉子眼」为由，扣下 2000 元押金不还。',
     '["翻出租房合同，看押金条款怎么约定的", "正常使用痕迹（钉子眼、墙面自然老化）不属损坏", "与房东书面协商，保留聊天记录", "可找社区调解、拨打 12345，或起诉（金额小，程序快）"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published'),

    ('dianche-pengzhuang',
     '下班路上被电动车撞了，第一步做什么？',
     '别急着私了也别急着吵——就像手机屏幕碎了先截图，路上出事故第一件事是「固定证据」，其次才是谈责任。',
     '交通类', 'traffic',
     '["交通事故", "电动车", "报警"]',
     '晚高峰骑车下班，被一辆逆行电动车撞倒，对方说「给你 200 块私了吧」。',
     '["先确认人身安全，受伤立即拨打 120", "报警 122，等交警出具《道路交通事故认定书》", "拍现场照片：车辆位置、刹车痕、周边监控位置", "私了有风险：伤情后发（如脑震荡）将无处追偿"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published'),

    ('loudong-chaozhu',
     '楼上装修吵翻天，除了忍还能怎么办？',
     '楼层之间就像共享一张桌子——你有敲桌子的自由，但不能在别人睡觉时敲。噪音权是有边界的，越界就要管。',
     '邻里 / 名誉类', 'neighbor',
     '["噪音", "相邻权", "物业"]',
     '楼上连续两周早 7 点开始电钻装修，沟通后对方说「我装修我自由」。',
     '["先查当地装修时间规定（多数城市：工作日 8:00–12:00、14:00–18:00）", "记录噪音时间 + 录音录像，形成证据", "找物业出面协调（装修一般有保证金约束）", "仍无效可报警或依据《噪声污染防治法》向城管投诉"]',
     '[]',
     '2026-09-22', '2026-09-22', '2026-09-22', 'AI 起草 + 律师复核', '待复核（mock）', 'published');

INSERT INTO laws (card_slug, name, text, source_url, sort_order) VALUES
    ('gongsi-quantui', '《劳动合同法》第 36 条',
     '用人单位与劳动者协商一致，可以解除劳动合同。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3OWFmZmUzMDE3OWJhNTc0NzdmNTAwOTU', 1),
    ('gongsi-quantui', '《劳动合同法》第 46 条',
     '用人单位依照本法第三十六条规定向劳动者提出解除劳动合同并与劳动者协商一致解除劳动合同的，应当向劳动者支付经济补偿。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3OWFmZmUzMDE3OWJhNTc0NzdmNTAwOTU', 2),
    ('gongsi-quantui', '《劳动合同法》第 47 条',
     '经济补偿按劳动者在本单位工作的年限，每满一年支付一个月工资的标准向劳动者支付。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3OWFmZmUzMDE3OWJhNTc0NzdmNTAwOTU', 3),
    ('guoqi-shipin', '《食品安全法》第 148 条',
     '生产不符合食品安全标准的食品或者经营明知是不符合食品安全标准的食品，消费者除要求赔偿损失外，还可以向生产者或者经营者要求支付价款十倍或者损失三倍的赔偿金；增加赔偿的金额不足一千元的，为一千元。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE4YWFhNzI5YzAxYWFjZDUxNzQ4NTBhOTU', 1),
    ('pengyou-jietiao', '《民法典》第 667 条',
     '借款合同是借款人向贷款人借款，到期返还借款并支付利息的合同。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YWIyNjE1OTAxN2FiNDA2NjE1OTAyMTU', 1),
    ('pengyou-jietiao', '《民法典》第 188 条',
     '向人民法院请求保护民事权利的诉讼时效期间为三年。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YWIyNjE1OTAxN2FiNDA2NjE1OTAyMTU', 2),
    ('fangdong-bu-tui-yajin', '《民法典》第 714 条',
     '承租人应当妥善保管租赁物，因保管不善造成租赁物毁损、灭失的，应当承担赔偿责任。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YWIyNjE1OTAxN2FiNDA2NjE1OTAyMTU', 1),
    ('fangdong-bu-tui-yajin', '《民法典》第 733 条',
     '租赁期限届满，承租人应当返还租赁物。返还的租赁物应当符合按照约定或者根据租赁物的性质使用后的状态。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YWIyNjE1OTAxN2FiNDA2NjE1OTAyMTU', 2),
    ('dianche-pengzhuang', '《道路交通安全法》第 76 条',
     '机动车发生交通事故造成人身伤亡、财产损失的，由保险公司在机动车第三者责任强制保险责任限额范围内予以赔偿……',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YzNjMzRiNTAxN2M0NjQwZjNiYzAxMTU', 1),
    ('loudong-chaozhu', '《噪声污染防治法》第 58 条',
     '对已竣工交付使用的住宅楼、商铺、办公楼等建筑物进行室内装修活动，应当按照规定限定作业时间，采取有效措施，防止、减轻噪声污染。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE4MjBiZDU3ZTAxODIwY2JhMTExZTAxMzA', 1),
    ('loudong-chaozhu', '《民法典》第 288 条',
     '不动产的相邻权利人应当按照有利生产、方便生活、团结互助、公平合理的原则，正确处理相邻关系。',
     'https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3YWIyNjE1OTAxN2FiNDA2NjE1OTAyMTU', 2);
